id = "mlir"
name = "MLIR"
version = "0.1.0"
schema_version = 1
authors = ["feichai0017 <songguocheng348@gmail.com>"]
description = "MLIR and TableGen language support for Zed."
repository = "https://github.com/feichai0017/mlir-zed"

[grammars.mlir]
repository = "https://github.com/artagnon/tree-sitter-mlir"
commit = "1cff1bf79135f8effef87d7cee9d3b26d1970ee9"

[grammars.tablegen]
repository = "https://github.com/Flakebi/tree-sitter-tablegen"
commit = "3e9c4822ab5cdcccf4f8aa9dcd42117f736d51d9"

[language_servers.mlir-lsp]
name = "MLIR LSP"
language = "MLIR"

[language_servers.mlir-lsp.language_ids]
MLIR = "mlir"

[language_servers.tblgen-lsp]
name = "TableGen LSP"
language = "TableGen"

[language_servers.tblgen-lsp.language_ids]
TableGen = "tablegen"
